### ISSUE TITLE
Chapter 6, build_interface() is missing some defaults/good coding form practices

### ISSUE THREAD

**Issue by commanderguy3001** [ClaudeMetz/UntitledGuiGuide#3]
As per Title, in Chapter 6, the new `local function build_interface()` should set the `enabled` tag for the slider and textfield to the current `player_global.controls_active`, since otherwise the default might be changed, and the controls should be deactivated but are still enabled in the GUI by default.

**Comment by ClaudeMetz** [comment]
Hi, appreciate the comment. That would indeed be better, I'll be sure to change it, thanks.

**Comment by ClaudeMetz** [comment]
Fixed
