### ISSUE TITLE
Ch 8 - Elements refactor and starting with a weird save

### ISSUE THREAD

**Issue by NIronwolf** [ClaudeMetz/UntitledGuiGuide#4]
First, thank you so much for writing up this tutorial.  I went from zero to being able to mitigate an issue I had with how I ended up progressing through the tutorial!

So long about say chapter 5 I ended up making a save.  This save had the GUI open.  By the time I'd worked through the updates in Chapter 8 to reference the GUI with the player_global.elements table there wasn't any way to close because the GUI wasn't made with the changes from Chapter 7 so that E and Escape wouldn't even try either.  Basically the GUI was lost out there.

So I updated the info.json version number to get .on_configuration_changed to run and added a bit of code there to hunt down the old GUI and get it to close it.

Here is the code if you want to make a supplemental note about really messing up your state/migration.

```lua
script.on_configuration_changed(function(config_changed_data)
    if config_changed_data.mod_changes["GUITutorial"] then
        for _, player in pairs(game.players) do
            local player_global = global.players[player.index]
            if not player_global.elements then
                player_global.elements = {}
                player_global.elements.main_frame = player.gui.screen.ugg_main_frame
            end
            local main_frame = player_global.elements.main_frame
            if main_frame ~= nil then toggle_interface(player) end
        end
    end
end)
```

**Comment by ClaudeMetz** [comment]
Hello, happy to hear it's been helpful! That's a nice fix you found there, but I don't think it's quite appropriate for the tutorial. It's not really expected that you save the individual steps, and I feel like this is a bit of a distraction, so it's better to leave out imo. Either way, appreciate the feedback.

**Comment by NIronwolf** [comment]
Oh I agree it's out of scope, but it can live here in closed issue.  :D

**Comment by ClaudeMetz** [comment]
I see, sure thing!
